export const questionKeys = {
    Ten99: "company_has_1099",
    benefitsKind: "benefits_features",
    businessKind: "payroll_industry",
    businessStructure: "company_structure",
    coverages: "coverages_features",
    coverageStart: "insurance_effective",
    currentPayroll: "payroll_method",
    email: "contact_email",
    existingCoverage: "insurance_current",
    expenses: "expenses",
    firstName: "contact_first_name",
    headcount: "company_headcount",
    hrFeatures: "hr_features",
    lastName: "contact_last_name",
    numOwners: "company_members",
    otherServices: "other_features",
    payrollThisYear: "payroll_current",
    revenue: "company_est_revenues",
    textOptIn: "contact_textconsent",
    w2: "company_has_w2",
    phoneNumber: "contact_phone",
    whatYouDo: "company_industry",
    whatState: "company_state"

}